### ISSUE TITLE
Update: collegefeed.html

### ISSUE THREAD

**Issue by dhruvpatel-9** [divyagiridhar/SE_Project_2#10]
There are some changes made in the collegefeed.html, front-end of the pagination feature, right @ravighevariya10 ?

**Comment by ravighevariya10** [comment]
Yes! But I would like to know that would it be in Principal Dashboard section or complaints?

**Comment by ravighevariya10** [comment]
No, its UI part so it's gonna be under collegefeed.html file.

**Comment by ravighevariya10** [comment]
It's linked with the views.py @Manan1612.

**Comment by ravighevariya10** [comment]
I just updated the collegefeed.html Can anyone check it? @Manan1612 @dhruvpatel-9 @divyagiridhar and @ShreyasTitus

**Comment by dhruvpatel-9** [comment]
You forgot to merge it in the main branch

**Comment by ravighevariya10** [comment]
Yaa!

Now, I did it.
