### ISSUE TITLE
Failing Test Cases

### ISSUE THREAD

**Issue by Manan1612** [divyagiridhar/SE_Project_2#19]
pages.yml automated page generation is failing, Can you please check that @dhruvpatel-9?

**Comment by dhruvpatel-9** [comment]
> I think @divyagiridhar need to do it, as only the repository owner can do it

@divyagiridhar can you setup the GitHub Pages thing?

**Comment by dhruvpatel-9** [comment]
Okay, she created the page, I updated it, and now the respective test is passing, i.e. GitHub Page with Jekyll
