### ISSUE TITLE
New Panel: Entire Principal Panel

### ISSUE THREAD

**Issue by divyagiridhar** [divyagiridhar/SE_Project_2#8]
Are we done with the entire principal panel?

**Comment by dhruvpatel-9** [comment]
Yeah @Manan1612 and I have almost completed the dashboard section, just some last minute changes then we will upload the respective file

**Comment by dhruvpatel-9** [comment]
I think @ravighevariya10 has completed the Principal Complaints section as well, right? @ravighevariya10

**Comment by ravighevariya10** [comment]
I am going to upload it by tonight.

**Comment by ravighevariya10** [comment]
I have uploaded the principalComplains.html

Request you all to check my work.

**Comment by dhruvpatel-9** [comment]
We have completed and uploaded the respective file
